variable "oci_tenancy_ocid" {}
variable "oci_user_ocid" {}
variable "oci_fingerprint" {}
variable "oci_private_key_path" {}
variable "oci_compartment_ocid" {}
variable "oci_region" {}
variable "ssh_public_key" {}
variable "oci_atp_admin_password" {}
variable "oci_atp_db_name" {}
variable "oci_atp_db_displayname" {}
variable "oci_atp_db_workload" {}
variable "oci_atp_db_cores" {}
variable "oci_atp_db_storage_tb" {}
variable "oci_service_vcn_cidr" {}
variable "oci_client_subnet_cidr" {}
variable "oci_azure_provider_ocid" {}
variable "oci_base_image" {}
variable "arm_subscription_id" {}
variable "arm_client_id" {}
variable "arm_client_secret" {}
variable "arm_tenant_id" {}
variable "arm_region" {}
variable "arm_image_publisher" {}
variable "arm_image_offer" {}
variable "arm_image_sku" {}
variable "arm_image_version" {}
variable "arm_expressroute_sku" {}
variable "arm_vnet_cidr" {}
variable "arm_client_subnet_cidr" {}
variable "arm_gw_subnet_cidr" {}
variable "peering_net" {}

